{% set name = "django-tag-parser" %}
{% set version = "3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-tag-parser-{{ version }}.tar.gz
  sha256: 903cd4bf3692c8c060770ca2b9d6e74e4ee52d6078308852acffe1ef4a49e0f7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - django
  run:
    - python >={{ python_min }}
    - django

test:
  imports:
    - tag_parser
    - tag_parser.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/edoburu/django-tag-parser
  summary: Micro-library to easily write custom Django template tags
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
